export const content = {
  id: {
    nav: {
      home: "Beranda",
      archives: "Arsip",
      add: "Tambah",
      settings: "Pengaturan",
      logout: "Keluar",
    },
    settings: {
      title: "Pengaturan",
      appearance: "Tampilan",
      chooseTheme: "Pilih Tema",
      light: "Terang",
      dark: "Gelap",
      language: "Bahasa",
      chooseLanguage: "Pilih Bahasa",
      appInfo: "Info Aplikasi",
      version: "Versi",
      status: "Status",
      online: "Online",
      copyright: "Catatan Pribadi Premium",
    },
    home: {
      activeNotes: "Catatan Aktif",
      title: "Catatan Saya",
      description: "Simpan ide-idemu agar tetap teratur dan mudah diakses.",
      searchPlaceholder: "Cari catatan...",
      empty: "Tidak ada catatan aktif",
      loading: "Memuat catatan...",
    },
    archives: {
      title: "Catatan Arsip",
      description: "Catatan yang tersimpan dan aman.",
      empty: "Tidak ada catatan arsip",
    },
    noteList: {
      emptySearch: "Tidak ada catatan ditemukan",
      emptyActive: "Mulai tambahkan catatan untuk melihatnya di sini.",
      emptyArchived: "Mulai tambahkan catatan arsip untuk melihatnya di sini.",
    },
    detail: {
      notFound: "Catatan tidak ditemukan",
      notFoundDescription: "Catatan tidak ditemukan atau telah dihapus.",
      backHome: "Kembali ke Beranda",
      goBack: "Kembali",
      archivedStatus: "Terarsip",
      archive: "Arsipkan",
      unarchive: "Batal Arsip",
      delete: "Hapus",
    },
    addNote: {
      title: "Tambah Catatan",
      description: "Catat idemu dengan format yang kaya.",
      titlePlaceholder: "Judul catatan...",
      bodyPlaceholder: "Tulis catatanmu disini...",
      save: "Simpan",
      cancel: "Batal",
      tipsTitle: "Tips Edit",
      tipsDescription: "Gunakan tombol cepat keyboard untuk menformat:",
      saving: "Menyimpan...",
      limit: "Sisa karakter",
    },
    auth: {
      loginTitle: "Masuk",
      registerTitle: "Daftar",
      email: "Email",
      password: "Kata Sandi",
      confirmPassword: "Konfirmasi Kata Sandi",
      name: "Nama",
      loginButton: "Masuk",
      registerButton: "Daftar",
      haveAccount: "Sudah punya akun?",
      noAccount: "Belum punya akun?",
      loginHere: "Masuk disini",
      registerHere: "Daftar disini",
    },
    notFound: {
      title: "Halaman Tidak Ditemukan",
      description: "Halaman yang kamu cari tidak ada atau telah dihapus.",
      backButton: "Kembali ke Beranda",
    },
    common: {
      success: "Berhasil",
      error: "Gagal",
      warning: "Peringatan",
    },
    common: {
      success: "Berhasil",
      error: "Gagal",
      warning: "Peringatan",
    },
    alerts: {
      noteArchived: "Catatan diarsipkan!",
      noteUnarchived: "Catatan batal diarsipkan!",
      noteDeleted: "Catatan dihapus!",
      noteSaved: "Catatan berhasil disimpan!",
      failedArchive: "Gagal mengarsipkan catatan",
      failedUnarchive: "Gagal membatalkan arsip catatan",
      failedDelete: "Gagal menghapus catatan",
      failedSave: "Gagal menyimpan catatan",
      loginSuccess: "Berhasil login",
      loginError: "Email atau kata sandi salah",
      registerSuccessLogin: "Akun dibuat dan berhasil login!",
      registerSuccess: "Akun dibuat! Silakan login manual.",
      registerError: "Registrasi gagal",
      passwordMismatch: "Kata sandi tidak sama",
      fillAllFields: "Mohon isi judul dan isi catatan",
      bodyLength: "Isi catatan minimal 10 karakter",
    },
  },
  en: {
    nav: {
      home: "Home",
      archives: "Archives",
      add: "Add",
      settings: "Settings",
      logout: "Logout",
    },
    settings: {
      title: "Settings",
      appearance: "Appearance",
      chooseTheme: "Choose Theme",
      light: "Light",
      dark: "Dark",
      language: "Language",
      chooseLanguage: "Choose Language",
      appInfo: "App Info",
      version: "Version",
      status: "Status",
      online: "Online",
      copyright: "Premium Personal Notes",
    },
    home: {
      activeNotes: "Active Notes",
      title: "My Notes",
      description: "Keep your thoughts organized and accessible.",
      searchPlaceholder: "Search notes...",
      empty: "No active notes",
      loading: "Loading notes...",
    },
    archives: {
      title: "Archived Notes",
      description: "Your stored and protected thoughts.",
      empty: "No archived notes",
    },
    noteList: {
      emptySearch: "No notes found",
      emptyActive: "Start adding some notes to see them here.",
      emptyArchived: "Start adding some archived notes to see them here.",
    },
    detail: {
      notFound: "Note not found",
      notFoundDescription:
        "The note you're looking for doesn't exist or has been removed.",
      backHome: "Back to Home",
      goBack: "Go back",
      archivedStatus: "Archived",
      archive: "Archive",
      unarchive: "Unarchive",
      delete: "Delete",
    },
    addNote: {
      title: "Add Note",
      description: "Capture your thoughts with rich formatting.",
      titlePlaceholder: "Note title...",
      bodyPlaceholder: "Write your note here...",
      save: "Save",
      cancel: "Cancel",
      tipsTitle: "Editing Tips",
      tipsDescription:
        "You can use standard keyboard shortcuts for formatting:",
      saving: "Saving...",
      limit: "Characters left",
    },
    auth: {
      loginTitle: "Login",
      registerTitle: "Register",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      name: "Name",
      loginButton: "Login",
      registerButton: "Register",
      haveAccount: "Already have an account?",
      noAccount: "Don't have an account?",
      loginHere: "Login here",
      registerHere: "Register here",
    },
    notFound: {
      title: "Page not found",
      description:
        "The page you're looking for doesn't exist or has been removed.",
      backButton: "Back to Home",
    },
    common: {
      success: "Success",
      error: "Error",
      warning: "Warning",
    },
    alerts: {
      noteArchived: "Note archived!",
      noteUnarchived: "Note unarchived!",
      noteDeleted: "Note deleted!",
      noteSaved: "Note saved successfully!",
      failedArchive: "Failed to archive note",
      failedUnarchive: "Failed to unarchive note",
      failedDelete: "Failed to delete note",
      failedSave: "Failed to save note",
      loginSuccess: "Login successful",
      loginError: "Invalid credentials",
      registerSuccessLogin: "Account created and logged in!",
      registerSuccess: "Account created! Please sign in manually.",
      registerError: "Registration failed",
      passwordMismatch: "Passwords do not match",
      fillAllFields: "Please fill in both title and body",
      bodyLength: "Body must be at least 10 characters long",
    },
  },
};
